// @ts-check
import { defineConfig } from "astro/config";
import starlight from "@astrojs/starlight";
import sitemap from "@astrojs/sitemap";

// Deployed to GitHub Pages at https://luxanimi.github.io/MailGrail/, so every
// internal link must carry the base. Use the href() helper in src/lib/href.ts
// rather than writing "/..." by hand -- a root-relative href works in `astro
// dev` and 404s in production, which is the classic way a Pages site breaks.
export default defineConfig({
  site: "https://luxanimi.github.io",
  base: "/MailGrail",
  trailingSlash: "ignore",

  // /setup is the URL `npx setup-mailgrail-app` prints when it finishes. Every
  // published copy of that package hard-codes it forever, so it stays an alias
  // rather than the real path -- the page behind it can be renamed or re-filed
  // and only this line changes. scripts/check-handoff.mjs fails the build if
  // this and the constant in the scaffolder ever disagree.
  //
  // /docs is here because Starlight generates no index for the docs root: every
  // page lives under a group, so the bare /docs a reader gets by truncating a
  // URL would otherwise 404.
  // Note the destinations carry the base and the keys do not: Astro applies
  // `base` when it *matches* a redirect, but writes the destination through
  // verbatim. Drop the prefix here and /MailGrail/setup forwards to
  // /docs/... -- off the deployment entirely, and green in `astro dev`.
  redirects: {
    "/setup": "/MailGrail/docs/getting-started/build-integration",
    "/docs": "/MailGrail/docs/getting-started/introduction",
  },

  integrations: [
    starlight({
      title: "MailGrail",
      description:
        "Type-safe email templates using React and MJML. Preview in a browser, compile to a portable template your backend renders on its own.",

      logo: {
        src: "./src/assets/mark.svg",
        alt: "MailGrail",
        replacesTitle: false,
      },

      social: [
        {
          icon: "github",
          label: "GitHub",
          href: "https://github.com/LuxAnimi/MailGrail",
        },
      ],

      // Docs live under src/content/docs/docs/** so Starlight serves them at
      // /docs/*, leaving / free for the custom landing page in src/pages.
      //
      // Autogenerated per directory rather than listed by slug: an explicit
      // list is a second place to forget a page, and a stale entry fails the
      // whole build. Order inside each group comes from `sidebar.order` in
      // each file's frontmatter.
      sidebar: [
        {
          label: "Getting started",
          items: [{ autogenerate: { directory: "docs/getting-started" } }],
        },
        {
          label: "Guides",
          items: [{ autogenerate: { directory: "docs/guides" } }],
        },
        {
          label: "Reference",
          items: [{ autogenerate: { directory: "docs/reference" } }],
        },
      ],

      customCss: ["./src/styles/brand.css", "./src/styles/docs.css"],

      components: {
        Head: "./src/components/docs/Head.astro",
      },

      editLink: {
        baseUrl:
          "https://github.com/LuxAnimi/MailGrail/edit/main/website/src/content/docs/",
      },

      lastUpdated: false,
      credits: false,
    }),

    sitemap(),
  ],
});
