// @ts-check
import { defineConfig } from "astro/config";
import starlight from "@astrojs/starlight";
import sitemap from "@astrojs/sitemap";

// Deployed to GitHub Pages at https://luxanimi.github.io/MailGrail/, so every
// internal link must carry the base. Use the href() helper in src/lib/href.ts
// rather than writing "/..." by hand -- a root-relative href works in `astro
// dev` and 404s in production, which is the classic way a Pages site breaks.
export default defineConfig({
  site: "https://luxanimi.github.io",
  base: "/MailGrail",
  trailingSlash: "ignore",

  integrations: [
    starlight({
      title: "mailgrail",
      description:
        "Type-safe email templates using React and MJML. Preview in a browser, compile to a portable template your backend renders on its own.",

      logo: {
        src: "./src/assets/mark.svg",
        alt: "mailgrail",
        replacesTitle: false,
      },

      social: [
        {
          icon: "github",
          label: "GitHub",
          href: "https://github.com/LuxAnimi/MailGrail",
        },
      ],

      // Docs live under src/content/docs/docs/** so Starlight serves them at
      // /docs/*, leaving / free for the custom landing page in src/pages.
      //
      // Autogenerated per directory rather than listed by slug: an explicit
      // list is a second place to forget a page, and a stale entry fails the
      // whole build. Order inside each group comes from `sidebar.order` in
      // each file's frontmatter.
      sidebar: [
        {
          label: "Getting started",
          items: [{ autogenerate: { directory: "docs/getting-started" } }],
        },
        {
          label: "Guides",
          items: [{ autogenerate: { directory: "docs/guides" } }],
        },
        {
          label: "Reference",
          items: [{ autogenerate: { directory: "docs/reference" } }],
        },
      ],

      customCss: ["./src/styles/brand.css", "./src/styles/docs.css"],

      components: {
        Head: "./src/components/docs/Head.astro",
      },

      editLink: {
        baseUrl:
          "https://github.com/LuxAnimi/MailGrail/edit/main/website/src/content/docs/",
      },

      lastUpdated: false,
      credits: false,
    }),

    sitemap(),
  ],
});
